#!/bin/bash
# oh baby a triple

INSTALLDIRECTORY="$HOME/.program_files"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
ITALIC='\033[3m'
UNDERLINE='\033[4m'
BLINKING='\033[5m'
REVERSE='\033[7m'
INVISIBLE='\033[8m'

function theThingWhatDoINameThisLMAO() {
    if [[ -f "$1" ]]; then
        if [[ "$1" == *.cinna ]]; then
            file_name=$(basename -- "$1")
            file_name_noext="${file_name%.*}"
            mkdir -p "$INSTALLDIRECTORY"

            echo -e "Installing package ${GREEN}$file_name_noext${NC}"
            echo -e "Unzipping ${GREEN}$file_name${NC}"
            unzip "$file_name" -d "$INSTALLDIRECTORY" > /dev/null

            if [[ -f "$INSTALLDIRECTORY/$file_name_noext-files.zip" ]]; then
                echo -e "Unzipping ${GREEN}$file_name_noext-files.zip${NC}"
                unzip "$INSTALLDIRECTORY/$file_name_noext-files.zip" -d "$INSTALLDIRECTORY/$file_name_noext-files" > /dev/null
                echo "Cleaning up ZIP file..."
                rm "$INSTALLDIRECTORY/$file_name_noext-files.zip"
            fi

            if [[ -f "$INSTALLDIRECTORY/metadata" ]]; then
                echo "Cleaning up meta file..."
                rm "$INSTALLDIRECTORY/metadata"
            fi

            chmod +x "$INSTALLDIRECTORY/$file_name_noext"
            echo -e "Package ${GREEN}$file_name_noext${NC} installed successfully."
        else
            echo -e "${RED}${BOLD}Error:${NC} Package ${GREEN}$file_name_noext${NC} could not be installed: Incorrect file type."
        fi
    else
        echo -e "${RED}${BOLD}Error:${NC} Package ${GREEN}$file_name${NC} not found."
    fi
}

theThingWhatDoINameThisLMAO $1